Title:			FORTHMACS
Author:			Mitch Bradley
Version:		3.00
Title From:		Documentation
Author From:		Documentation
Version From:		Documentation
Supplier:		Hanno Schwalm (hs@4thware.gerwin.net)
Date:			29/07/94
Keywords:		Programming languages ; Forth
Shareware:		No
Machine:		Archimedes
Operating system:	RISCOS
Memory requirements:	
Peripherals needed:	
Other s/ware needed:	
Directory:		micros/arch/riscos/c073
Date mounted/updated:	30/08/94
File names:		forthmacs.arc
Unarchived files:	38
Unarchived size:	265 kbytes
Omissions:		
See also:		TILEFORTH (a111), AFORTH (a293)

-------------------------------------------------------------------------------

Acquiring the package:

Download the archive file(s) and extract using SparkPlug 2
(see the "tools_help" file in micros/arch/riscos/tools for further info).


Description:

Forthmacs is Hanno Schwalm's port of Mitch Bradleys "Forthmacs 3.0".
This Risc-OS Forthmacs currently followes the Forth-83 standard in many 
ways, it's code has been written with portability to other platforms and 
former versions in mind.  It runs almost any software that has been 
written for 'Forthmacs' before or needs very little re-coding.  
